# Generated by Django 2.2.1 on 2019-05-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='pictures'),
        ),
    ]
